import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [4]:
import numpy as np

list_ = [ "1" , "2" , "3" , "4" , "5" ]
print(type(list_))

array_list = np.array(object = list_)
print(array_list)
print(type(array_list))

<class 'list'>
['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


the data type of variables list_ is list buit the data type of array_list is numpy nd array

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [11]:
list_ = [ "1" , "2" , "3" , "4" , "5" ]
print("data types of each element of variable list_")
for i in list_:
    
    print(i,type(i))

array_list = np.array(object = list_)
print("data types of each element of variable array_list")
for j in array_list:
    print(j,type(j))


data types of each element of variable list_
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
data types of each element of variable array_list
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

After the above changes the data type of variable list_ will remain list but the data type of each element of variable array_list will be integer.

In [15]:
list_ = [ "1" , "2" , "3" , "4" , "5" ]
print("data types of each element of variable list_")
for i in list_:
    print(i,type(i))

array_list = np.array(object = list_, dtype = int)
print("data types of each element of variable array_list")
for j in array_list:
    print(j,type(j))

data types of each element of variable list_
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
data types of each element of variable array_list
1 <class 'numpy.int32'>
2 <class 'numpy.int32'>
3 <class 'numpy.int32'>
4 <class 'numpy.int32'>
5 <class 'numpy.int32'>


Consider the below code to answer further questions:
    
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [21]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array.size)
print(num_array.shape)

6
(2, 3)


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [33]:
a = np.zeros((3, 3))
print(a)
#print(type(a))
print(a.size)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
(3, 3)


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [43]:
import numpy as np
id_array = np.identity(5,dtype=int)
print(id_array)
id_array.shape

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


(5, 5)